homepage:
    path: /
    controller: App\Controller\HomepageController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

logout:
    path: /logout
    controller: App\Controller\LoginController::logout

clientList:
    path: /client/list
    controller: App\Controller\ClientController::list

clientCreate:
    path: /client/create
    controller: App\Controller\ClientController::create
    methods: GET|POST

clientModify:
    path: /client/modify/{id}
    controller: App\Controller\ClientController::modify
    methods: GET|POST
    requirements:
        id: '\d+'